import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const operatorMono = localFont({
  variable: "--font-operator-mono",
  src: [
    {
      path: "../components/fonts/OperatorMono-Bold.otf",
      weight: "800",
      style: "normal",
    },
  ],
});

const operatorMonoItalic = localFont({
  variable: "--font-operator-mono-italic",
  src: [
    {
      path: "../components/fonts/OperatorMono-BoldItalic.otf",
      weight: "800",
      style: "italic",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${operatorMono.variable} ${operatorMonoItalic.variable} antialiased bg-[#0F1A19] overflow-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
